export const COUNT_ACTION_TYPES = {
    ADD: "ADD",
    SUB: "SUB",
    MULTIPLY: "MULTIPLY",
    DIVIDE: "DIVIDE",
    STORE_NUMBER: "STORE_NUMBER"
}

export const PERSON_ACTION_TYPES = {
    STORE_PERSON: "STORE_PERSON",
    REMOVE_PERSON: "REMOVE_PERSON"
}